### PR TITLE
show more than 25 options, only show active options

### PR DESCRIPTION
**Pull request by bnussbau**
* show up to 50 Options (Sales Channels, Payment Methods, Shipping Methods) instead of default 25
* only show active ShippingMethods, PaymentMethods and SalesChannels

### CODE REVIEW

**Comment by leduc92** [comment]
Hi @bnussbau , thanks for your pull request. I will merge it.
This feature is implemented on the core of Shopware since 6.4.0 version, then I highly recommend using the feature in core instead of using this plugin.

**Comment by bnussbau** [comment]
> Hi @bnussbau , thanks for your pull request. I will merge it.
> This feature is implemented on the core of Shopware since 6.4.0 version, then I highly recommend using the feature in core instead of using this plugin.

There are still many shops that are not yet ready for 6.4. For some this plugin solves a big problem 👍

**Comment by Guite** [comment]
Hello @leduc92,

can you please elaborate which feature is contained in Shopware 6.4.x core? Is the whole plugin obsolete now? Can't find any reference to a similar functionality in the [Shopware documentation](https://docs.shopware.com/en/shopware-6-de/after-order-payment-process?category=shopware-6-en/orders).

**Comment by leduc92** [comment]
Hi @Guite , there are a lot of new fields are added to Order in version 6.4. 
image

**Pull request merged**
